package com.libertad.mambu.domain.model

data class Onboarding(
    var firstname: String = "",
    var rs_segundonombre: String ="",
    var middlename: String = "",
    var lastname: String = "",
    var rs_fechanacimiento: String ="",
    var mobilephone: String ="",
    var rs_rfc : String = "",
    var rs_curp: String= "",
    var emailaddress1: String ="",
    var rs_genero: String = "",
    var rs_paisnacimiento: String="",
    var rs_lugarnacimiento: String = "",
    var rs_nacionalidad: String ="",
    var address1_line1: String = "",
    var address1_line2: String = "",
    var address1_line3: String ="",
    var address1_postalcode: String = "",
    var rs_entidadfederativa: String = "",
    var rs_municipio: String = "",
    var rs_colonia: String = "",
    var interviewid: String = "",
    var telephone1: String = "",
    var rs_coloniaid: String =  "",
    var rs_numerocuenta: String = "",
    var rs_numerocliente: String = "",
    var rs_cuentaclabemambu: String = "",
    var rs_claverastreo: String ="",
    var rs_clave: String ="",
    var rs_fechaapertura: String =""
)