steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/lsf-dev-cloudpak/spring-boot-originacion', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/lsf-dev-cloudpak/spring-boot-originacion']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'spring-boot-originacion'
      - '--image'
      - 'gcr.io/lsf-dev-cloudpak/spring-boot-originacion'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '9080'
